# Generated by Django 3.2.17 on 2023-02-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_restaurant_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
